---
- hosts: localhost
  gather_facts: True
  tasks: []

- hosts: localhost
  gather_facts: False
  become: True
  roles:
    - { name: ansible-role-travis-lxc }
  vars:
    ansible_ssh_interpreter: "{{ lookup('env','VIRTUAL_ENV') }}/python"
    host_quantity: 2
