language: python
python:
  - "2.7"
  - "3.6"
sudo: required
dist: trusty
cache:
  directories:
  - "$HOME/lxc"
  pip: true
env:
  - ANSIBLE_VERSION='<2.6.0' # 2.5.x
matrix:
  fast_finish: true
  include:
    - python: '2.7'
      env: ANSIBLE_GIT_VERSION='devel' # 2.6.x development branch
    - python: '2.7'
      env: ANSIBLE_VERSION='<2.5.0' # 2.4.x
    - python: '2.7'
      env: ANSIBLE_VERSION='<2.4.0' # 2.3.x
    - python: '2.7'
      env: LXC_DISTRO=ubuntu LXC_RELEASE=xenial TEST=_v0.6_compat # Backwards compatibility test
install:
- ls -lh $HOME/lxc
- if [ "$ANSIBLE_GIT_VERSION" ]; then pip install "https://github.com/ansible/ansible/archive/${ANSIBLE_GIT_VERSION}.tar.gz";
  elif [ "$ANSIBLE_VERSION" ]; then pip install "ansible${ANSIBLE_VERSION}";
  else pip install ansible; fi
- ansible --version
# The following is needed for default Ansible 2.3 installations
- 'sudo mkdir -p /etc/ansible/roles && sudo chown $(whoami): /etc/ansible/roles'
- git archive --format tar.gz HEAD > lae.travis-lxc.tar.gz && ansible-galaxy install
  lae.travis-lxc.tar.gz,$(git rev-parse HEAD),lae.travis-lxc && rm lae.travis-lxc.tar.gz
before_script: cd tests/
script:
- ansible-playbook -i inventory${TEST} deploy${TEST}.yml --syntax-check
- ansible-playbook -i inventory${TEST} -v deploy${TEST}.yml
- 'ANSIBLE_STDOUT_CALLBACK=debug unbuffer ansible-playbook -i inventory${TEST}
  -vv deploy${TEST}.yml > idempotency.log 2>&1 || (e=$?; cat idempotency.log; exit $e)'
- 'grep -A1 "PLAY RECAP" idempotency.log | grep -qP "changed=0 .*failed=0 .*" &&
  (echo "Idempotence: PASS"; exit 0) || (echo "Idempotence: FAIL"; exit 1)'
- ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook -i inventory${TEST} -v test.yml
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  irc:
    on_success: change
    channels:
      secure: "uNnWy3ToabL7W4mP2jTqdbV3do408Sl4N53D9T3vvcpCOLrdHeSagq+Juto3q4Z2bF/zpwHp05y5pJU0N3Fsb4W1C2jUnGvbwEYFRK+cTUsMUT+rrcHByF2e/nMBi1GEPysGfXtNMlEIe+rlKNTCFvfngnp2lTmcs4QBtQh+eS1YQBr8mdizCDWi28FygMTma87VdQ10Af0XkXWHgVHYfh4MARGfkMmCWjZqBHaKV5xTZ7xVzndGN7T3XiehRnD44iQNT6PaYZFRqUWV8S8BROhwOZIlgwEX3t/gxiGKLOHoI/cubm2H8aKEhSMl18MUZxET7CK4vwVpEnlqTQihsLkkuM7zfvsUWEQA03ZsZDAAnnIykbfQDMVBexOfZwv/5xdX5qTy2aghr7c/+LUf8N86Hj+TDGfWBioNhuPYBj5lghw0a+p002kKjjmgr2tTZpghIdHzmRqjne2ZbcIH3lBMWftzDHtBxuUTAaxaGP75VqH0JF5lGUvZL49VPtb8tGff0BVi0+YuHdlDAoIL6ACC6qQlgyVEZhZ170QS0Ez9s+pkMa1rpj4BsxBKZog3TKEad4K+CcewarwCgCEGxG2S4E1ugeZoCVtP8Gr4CC/51axhbATCPqYSQnNXKXo6vP3Gw3VBOcKx/Ku8uR+Kcdj7oEoAcJRF5eZFMG1y5Wk="
