---
- hosts: localhost
  gather_facts: True
  connection: local
  tasks: []

- hosts: localhost
  gather_facts: False
  connection: local
  become: True
  roles:
    - { name: ansible-role-travis-lxc }
  vars:
    host_quantity: 2
