---
language: python
python: "2.7"

sudo: required
dist: trusty

addons:
  apt:
    sources:
    - sourceline: ppa:ubuntu-lxc/stable
    packages:
    - python-pip
    - lxc
    - lxc-templates
    - lxc-dev
    - yum
    - debootstrap
    - expect-dev

cache:
  directories:
  - "$HOME/lxc/"
  pip: true

before_cache:
- mkdir $HOME/lxc
- sudo tar cf $HOME/lxc/cache.tar /var/cache/lxc/
- sudo chown $USER. $HOME/lxc/cache.tar

install:
- sudo tar xf $HOME/lxc/cache.tar -C / || echo "Didn't extract cache."
- pip install ansible lxc-python2
- ansible --version
- printf '[defaults]\nroles_path=../\nhost_key_checking=False\ncallback_whitelist=profile_tasks'
  >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook .travis-playbook.yml --syntax-check
  - ansible-playbook .travis-playbook.yml
  - unbuffer ansible-playbook .travis-playbook.yml >/tmp/idempotency.log 2>&1
  - 'grep -A1 "PLAY RECAP" /tmp/idempotency.log | grep -qP "changed=0.*failed=0" && (echo "Idempotence:
    PASS"; exit 0) || (echo "Idempotence: FAIL"; cat /tmp/idempotency.log; exit 1)'
  - sudo lxc-attach -n test01 -v PAGER=cat -- journalctl -xn

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
