language: python
python:
  - "2.7"
  - "3.6"
sudo: required
dist: trusty
cache:
  directories:
  - "$HOME/lxc"
  pip: true
env:
  - ANSIBLE_VERSION='<2.8.0' # 2.7.x
matrix:
  fast_finish: true
  include:
    - python: '2.7'
      env: ANSIBLE_GIT_VERSION='devel' # 2.8.x development branch
    - python: '2.7'
      env: ANSIBLE_VERSION='<2.7.0' # 2.6.x
    - python: '2.7'
      env: ANSIBLE_VERSION='<2.6.0' # 2.5.x
install:
- ls -lh $HOME/lxc
- if [ "$ANSIBLE_GIT_VERSION" ]; then pip install "https://github.com/ansible/ansible/archive/${ANSIBLE_GIT_VERSION}.tar.gz";
  else pip install "ansible${ANSIBLE_VERSION}"; fi
- ansible --version
- git archive --format tar.gz HEAD > lae.travis-lxc.tar.gz && ansible-galaxy install
  lae.travis-lxc.tar.gz,$(git rev-parse HEAD),lae.travis-lxc && rm lae.travis-lxc.tar.gz
before_script: cd tests/
script:
- ansible-playbook -i inventory deploy.yml --syntax-check
- ansible-playbook -i inventory -v deploy.yml
- 'ANSIBLE_STDOUT_CALLBACK=debug unbuffer ansible-playbook -vvi inventory
  deploy.yml > play.log || (e=$?; cat play.log; exit $e); printf "Idempotence: ";
  grep -A1 "PLAY RECAP" play.log | grep -qP "changed=0 .*failed=0 .*"
  && (echo "PASS"; exit 0) || (echo "FAIL"; cat play.log; exit 1)'
- ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook -i inventory -v test.yml
notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
      - https://t2d.idolactiviti.es/notify
