---
- hosts: localhost
  connection: local
  roles:
    - { name: ansible-role-travis-lxc }
  vars:
    template: "{{ lookup('env', 'LXC_DISTRO') }}"
    release: "{{ lookup('env', 'LXC_RELEASE') }}"
