---
- hosts: localhost
  connection: local
  gather_facts: True
  tasks: []

- hosts: localhost
  connection: local
  gather_facts: False
  become: True
  roles:
    - { name: lae.travis-lxc }
  vars:
    host_quantity: 2
