---
# tasks file for ansible-role-travis-lxc
- set_fact:
    ansible_python_interpreter: /opt/python/2.7.12/bin/python

- block:
  - name: Copy python-apt into Travis' virtualenv
    copy:
      src: /usr/lib/python2.7/dist-packages/apt
      dest: "/opt/python/2.7.12/lib/python2.7/site-packages/"

  - name: Configure LXC PPA
    apt_repository:
      repo: "ppa:ubuntu-lxc/stable"

  - name: Install needed packages
    apt:
      name: "{{ item }}"
      update_cache: yes
      cache_valid_time: 3600
      state: latest
    with_items: "{{ travis_lxc_packages }}"
  become: True

- name: Install needed Python libraries
  pip:
    name: "{{ travis_lxc_eggs }}"
    state: latest

- name: Create SSH directory for current user
  file:
    path: "~{{ ansible_user_id }}/.ssh"
    state: directory
    mode: 0700

- name: Generate local ssh-rsa key
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: true
    ssh_key_file: "~{{ ansible_user_id }}/.ssh/id_rsa"
    ssh_key_type: rsa
    ssh_key_comment: "{{ ansible_user_id }}@{{ ansible_hostname }}-lxctest"

- block:
  - include: "{{ template }}-{{ release }}.yml"

  - name: Wait for test containers to come online
    lxc_container:
      name: "{{ host_prefix }}{{ '%s' | format(item) }}"
      container_command: "until (grep -q '^up$' /sys/class/net/eth0/operstate); do printf . && sleep 1; done; sleep 2"
    changed_when: false
    register: containers
    with_sequence: count="{{ host_quantity | int }}" format="%02d"

  - debug: var=containers

  - name: Add test container(s) to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: "^.* {{ item.lxc_container.name }}.lxc"
      line: "{{ item.lxc_container.ips[0] }} {{ item.lxc_container.name }}.lxc"
    with_items: "{{ containers.results }}"

  - name: Create .ssh directory in containers
    file:
      path: "/var/lib/lxc/{{ item.lxc_container.name }}/rootfs/root/.ssh/"
      state: directory
      mode: 0700
    with_items: "{{ containers.results }}"

  - name: Copy current user's public key into containers
    copy:
      src: "~/.ssh/id_rsa.pub"
      dest: "/var/lib/lxc/{{ item.lxc_container.name }}/rootfs/root/.ssh/authorized_keys"
      mode: 0600
    with_items: "{{ containers.results }}"
  become: True

# vim:ft=ansible:
