---
# tasks file for ansible-role-travis-lxc
- set_fact:
    ansible_python_interpreter: "{{ lookup('env', 'VIRTUAL_ENV') }}/bin/python"
    container_config: "{{ container_config }} + {{ travis_lxc_network_config }}"

- include: validate_variables.yml
- include: travis_packaging_setup.yml

- name: Create SSH directory for current user
  file:
    path: "~{{ ansible_user_id }}/.ssh"
    state: directory
    mode: 0700

- name: Generate local ssh-rsa key
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: true
    ssh_key_file: "~{{ ansible_user_id }}/.ssh/id_rsa"
    ssh_key_type: rsa
    ssh_key_comment: "{{ ansible_user_id }}@{{ ansible_hostname }}-lxctest"

- block:
  - name: Create LXC containers for requested test profiles
    lxc_container:
      name: "{{ item.0.prefix | default(item.0.profile) }}{{ item.1 }}"
      template: "{{ item.0.profile.split('-').0 }}"
      template_options: >-
        {% set __profile = item.0.profile.split('-') %}
        --release {{ __profile.1 }}
        {% if __profile.0 in ['debian', 'ubuntu'] %}
        --mirror
        {% if __profile.0 == 'ubuntu' %}
        {{ __travis_ubuntu_mirror }}
        {% else %}
        http://deb.debian.org/debian
        {% endif %}
        --packages {{ (travis_lxc_profiles[item.0.profile]['packages'] + additional_packages) | join(',') }}
        {% endif %}
      container_config: "{{ container_config }}"
      state: started
    environment: "{{ travis_lxc_profiles[item.0.profile]['environment'] | default(omit) }}"
    register: __container_creation_jobs
    async: 7200
    poll: 0
    changed_when: false
    with_nested:
      - "{{ test_profiles }}"
      - "{{ test_host_suffixes }}"

  - name: Wait for container creation tasks to complete
    async_status:
      jid: "{{ item.ansible_job_id }}"
    register: __containers
    until: __containers.finished
    retries: 300
    with_items: "{{ __container_creation_jobs.results }}"

  - name: Wait until containers have active IP addresses
    lxc_container:
      name: "{{ item.lxc_container.name }}"
      container_command: "until (ip addr show eth0 up | grep -q 'inet '); do sleep 1; done"
    register: __container_addresses
    changed_when: false
    with_items: "{{ __containers.results }}"

  - name: Install packages in RHEL-based containers
    lxc_container:
      name: "{{ item.lxc_container.name }}"
      container_command: >-
        {% if item.invocation.module_args.template == 'fedora' %}
        dnf install -y
        {% else %}
        yum install -y
        {% endif %}
        {{ (travis_lxc_profiles[item.item.item.0.profile]['packages'] + additional_packages) | join(' ') }}
    register: __container_post_jobs
    async: 7200
    poll: 0
    changed_when: false
    with_items: "{{ __containers.results }}"
    when:
      - item | changed
      - "item.invocation.module_args.template is in ['centos', 'fedora']"

  - name: Wait for RHEL package installations to complete
    async_status:
      jid: "{{ item.ansible_job_id }}"
    register: __async_status
    until: __async_status.finished
    retries: 300
    with_items: "{{ __container_post_jobs.results }}"
    when: "'ansible_job_id' in item"

  - debug:
      var: __containers
      verbosity: 2

  - debug:
      var: __container_addresses
      verbosity: 2

  - set_fact:
      lxc_hosts: "{% set __hosts = [] %}{% for ct in (__container_addresses.results | map(attribute='lxc_container') | list) %}{{ __hosts.append({'name': ct.name, 'ip': ct.ips[0]}) }}{% endfor %}{{ __hosts }}"

  - name: Populate Travis' /etc/hosts with every container's addresses
    lineinfile:
      dest: /etc/hosts
      regexp: "^.* {{ item.name }}"
      line: "{{ item.ip }} {{ item.name }}.lxc {{ item.name }}"
    with_items: "{{ lxc_hosts }}"

  - name: Populate every container's /etc/hosts with every container's addresses
    template:
      src: hosts.j2
      dest: "/var/lib/lxc/{{ item.name }}/rootfs/etc/hosts"
    with_items: "{{ lxc_hosts }}"

  - name: Authorize local user to access all containers over SSH
    shell: >-
      mkdir -p 0700 /var/lib/lxc/{{ item.name }}/rootfs/root/.ssh/ &&
      cp ~{{ ansible_user_id }}/.ssh/id_rsa /var/lib/lxc/{{ item.name }}/rootfs/root/.ssh/authorized_keys &&
      chmod 0600 /var/lib/lxc/{{ item.name }}/rootfs/root/.ssh/authorized_keys
    args:
      creates: "/var/lib/lxc/{{ item.name }}/rootfs/root/.ssh/authorized_keys"
    with_items: "{{ lxc_hosts }}"
  become: true

- name: Collect SSH host keys from all containers
  shell: "ssh-keyscan {{ item.name }}.lxc {{ item.name }} > ~{{ ansible_user_id }}/.ssh/{{ item.name }}.pub"
  args:
    creates: "~{{ ansible_user_id }}/.ssh/{{ item.name }}.pub"
  with_items: "{{ lxc_hosts }}"

- name: Add all containers to current user's known_hosts
  blockinfile:
    marker: "# {mark} {{ item.name }}"
    content: "{{ lookup('file', '~' + ansible_user_id + '/.ssh/' + item.name + '.pub') }}"
    dest: "~{{ ansible_user_id }}/.ssh/known_hosts"
    create: yes
  with_items: "{{ lxc_hosts }}"

# vim:ft=ansible:
