---
- block:
  # This needs to be done using a command module because the apt module is
  # broken in the Travis CI virtualenv by default.
  - name: Install python3-apt systemwide
    shell: "apt update && apt install -y python3-apt"
    args:
      creates: /usr/lib/python3/dist-packages/apt
      warn: False
    retries: 3
  become: True

# After this task, the apt module can be used without problem.
- name: Install python-apt into virtualenv
  copy:
    src: "/usr/lib/python3/dist-packages/{{ item }}"
    dest: "{{ lookup('env', 'VIRTUAL_ENV') }}/lib/python3.6/site-packages/"
    remote_src: yes
  with_items:
    - apt
    - aptsources
    - apt_inst.cpython-36m-x86_64-linux-gnu.so
    - apt_pkg.cpython-36m-x86_64-linux-gnu.so

- block:
  - name: Install needed packages
    apt:
      name: "{{ travis_lxc_packages }}"
      update_cache: yes
      cache_valid_time: 3600
      state: latest
    retries: 3

  - name: Patch Fedora's LXC template for 28+ support
    patch:
      src: fedora-28-support.patch
      dest: /usr/share/lxc/templates/lxc-fedora

  - name: Ensure Fedora LXC template is executable
    file:
      path: /usr/share/lxc/templates/lxc-fedora
      mode: 0755

  - name: Patch Alpine's LXC template to not fail on mknod
    patch:
      src: alpine-mknod.patch
      dest: /usr/share/lxc/templates/lxc-alpine

  - name: Ensure Alpine LXC template is executable
    file:
      path: /usr/share/lxc/templates/lxc-alpine
      mode: 0755
  become: True

- name: Install LXC Python library
  pip:
    name: "{{ 'https://github.com/lxc/python3-lxc/archive/python3-lxc-3.0.4.tar.gz' if ansible_python.version.major == 3 else 'lxc_python2' }}"
    virtualenv: "{{ lookup('env', 'VIRTUAL_ENV') }}"
  retries: 3

- name: Identify Travis CI's local Ubuntu mirror
  shell: 'apt-cache policy python | grep -m1 -oP "https?://.*?/ubuntu"'
  changed_when: False
  register: _travis_ubuntu_mirror_lookup

- name: Set fact for which mirror to use for Ubuntu LXC containers
  set_fact:
    _travis_ubuntu_mirror: "{{ _travis_ubuntu_mirror_lookup.stdout if _travis_ubuntu_mirror_lookup.stdout != '' else 'http://mirror.math.princeton.edu/pub/ubuntu' }}"
