---
- block:
  - name: Install libapt-pkg-dev as build dependency for python-apt
    command: "apt-get install -y libapt-pkg-dev=1.2.10"
    args:
      creates: /usr/lib/x86_64-linux-gnu/libapt-pkg.so

  - name: Clone the python-apt source repository
    git:
      repo: https://git.launchpad.net/python-apt
      dest: /usr/local/src/python-apt
      version: 1.1.0_beta5
      depth: 1

  - name: Install the python-apt library from local source
    pip:
      name: file:///usr/local/src/python-apt
      virtualenv: "{{ lookup('env', 'VIRTUAL_ENV') }}"

  - name: Configure LXC PPA
    apt_repository:
      repo: "ppa:ubuntu-lxc/stable"

  - name: Install needed packages
    apt:
      name: "{{ item }}"
      update_cache: yes
      cache_valid_time: 3600
      state: latest
    with_items: "{{ travis_lxc_packages }}"
  become: True

- name: Install lxc-python2 if running with Python 2
  pip:
    name: lxc-python2
    state: latest
    virtualenv: "{{ lookup('env', 'VIRTUAL_ENV') }}"
  when: ansible_python.version.major == 2

- name: Identify Travis CI's local Ubuntu mirror
  shell: 'apt-cache policy python | grep -m1 -oP "https?://.*?/ubuntu"'
  changed_when: False
  register: __travis_ubuntu_mirror_lookup

- name: Set fact for which mirror to use for Ubuntu LXC containers
  set_fact:
    __travis_ubuntu_mirror: "{{ __travis_ubuntu_mirror_lookup.stdout if __travis_ubuntu_mirror_lookup.stdout != '' else 'http://mirror.math.princeton.edu/pub/ubuntu' }}"
