---
- name: Create Ubuntu Precise Pangolin (12.04) test container(s)
  lxc_container:
    name: "{{ host_prefix }}{{ '%s' | format(item) }}"
    template: "{{ template }}"
    template_options: "--release {{ release }} --mirror http://mirrors.us.kernel.org/ubuntu --packages python,ca-certificates,curl,sudo"
    container_config: "{{ container_config }}"
    state: started
  with_sequence: count="{{ host_quantity | int }}" format="%02d"

# vim:ft=ansible:
