---
# Backwards compatibility with environment-specified profiles in <0.7.0
- set_fact:
    test_profiles:
      - profile: "{{ lookup('env', 'LXC_DISTRO') | default(travis_lxc_default_test_profiles.0.profile.split('-').0, true) }}-{{ lookup('env', 'LXC_RELEASE') | default(travis_lxc_default_test_profiles.0.profile.split('-').1, true) }}"
        prefix: "{{ host_prefix | default(travis_lxc_default_test_profiles.0.prefix, true) }}"
  when: test_profiles is not defined

- assert:
    that:
      - test_profiles is iterable
      - test_profiles is not string
    msg: "The variable 'test_profiles' must be a list."

- assert:
    that: "__missing_profiles == []"
    msg: "The following test_profiles are missing the 'profile' key:
      {% for index in __missing_profiles %}\
      test_profiles[{{ index }}] == {{ test_profiles[index] | to_yaml | trim }}\
      {% if not loop.last %}, {% endif %}\
      {% endfor %}"
  vars:
    __missing_profiles: "\
      [\
      {% for test_profile in test_profiles %}\
      {% if 'profile' not in test_profile %}\
      {{ loop.index0 }}, \
      {% endif %}\
      {% endfor %}\
      ]"

- assert:
    that: "__invalid_profiles == []"
    msg: "The following profile(s) cannot be used: {{ __invalid_profiles | join(' ') }}. If you believe this is a mistake, please open an issue."
  vars:
    __invalid_profiles: "{{ (test_profiles | map(attribute='profile') | list) | difference(travis_lxc_profiles.keys()) }}"

- set_fact:
    lxc_cache_profiles: "{{ test_profiles | map(attribute='profile') | list }}"
  when: lxc_cache_profiles is not defined

- assert:
    that: "__invalid_cache_profiles == []"
    msg: "The following cache profile(s) were specified but not present in test_profiles: {{ __invalid_cache_profiles | join(' ') }}"
  when: lxc_cache_enabled
  vars:
    __invalid_cache_profiles: "{{ lxc_cache_profiles | difference(test_profiles | map(attribute='profile') | list) }}"

- assert:
    that: "\
      {% set __found_prefixes = [] %}\
      {% for test_profile in test_profiles %}\
      {% if 'prefix' in test_profile %}\
      {{ __found_prefixes.append(test_profile.prefix) }}\
      {% else %}\
      {{ __found_prefixes.append(test_profile.profile) }}\
      {% endif %}\
      {% endfor %}\
      {{ (__found_prefixes | unique | list | length) == ( __found_prefixes | list | length )}}"
    msg: "There are duplicate prefixes specified in 'test_profiles'. Please ensure that you are not reusing prefix names for multiple profiles or using prefixes that conflict with profile names."

# Backwards compatibility with host_quantity variable from <0.7.0
# These conditions make it so that if user specifies test_hosts_per_profile and
# host_quantity together, test_hosts_per_profile will take precedence.
- set_fact:
    test_hosts_per_profile: "{{ host_quantity }}"
  when:
    - host_quantity is defined
    - test_hosts_per_profile is not defined

- debug:
    msg: "Both 'test_hosts_per_profile' and 'test_host_suffixes' have been defined. 'test_hosts_per_profile' will be ignored."
  when: test_hosts_per_profile is defined and test_host_suffixes is defined

# The following set_fact ensures that:
# - if test_hosts_per_profile isn't specified, we default to 1
# - if test_host_suffixes isn't specified, we generate a list of zero-padded
#   number suffixes based on test_hosts_per_profile
- set_fact:
    test_host_suffixes: "[{% for n in range(0, test_hosts_per_profile | default(1) | int) %}'{{ '%02d' | format(n+1) }}',{% endfor %}]"
  when: test_host_suffixes is not defined
